name: Django Tests

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master


# on:
#     schedule:
#         - cron: ''


jobs:
    build:

        runs-on: ubuntu-latest

        step:
            - uses: actions/checkout@v2
            - name: setup up python 3.10
              uses: action/setup-python@v2
              with:
                python-version: 3.10

            - name: Install dependencies
              run: python -m pip install --upgrade pip 
              run: pip install -r requirements.txt

            - name: Lint With Flake8
             run: pip install flake8 
             run: flake8

            - name: Coverage Report
              run: pip install coverage 
              run: coverage run manage.py test
              run: coverage report

            - name: DJango Testing
              run: python3 manage.py test
